common: &common
  adapter: postgresql
  username: # PostgreSQL Username
  password: # PostgreSQL Password
  host: localhost
  port: 5432

development:
  adapter: sqlite3
  database: odhk_development

test:
  <<: *common
  database: odhk_test

production:
  <<: *common
  database: odhk_production


