common: &common
  adapter: sqlite3
  username: odhk
  password: guidance # from psql setup, see Postgresql
  host: localhost
  port: 5432

development:
  <<: *common
  database: odhk_development

test:
  <<: *common
  database: odhk_test

production:
  <<: *common
  database: odhk_production
