common: &common
  adapter: postgresql
  username: odhk
  password: guidance # from psql setup, see Postgresql
  host: localhost
  port: 5432

development:
  # <<: *common
  # database: odhk_development
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000

test:
  <<: *common
  database: odhk_test

production:
  <<: *common
  database: odhk_production
